import type { LitElement } from "lit-element/lit-element.js";

import type RWaAnimatedImage from '@web.awesome.me/webawesome-pro/dist/components/animated-image/animated-image.js';
import type RWaAnimation from '@web.awesome.me/webawesome-pro/dist/components/animation/animation.js';
import type RWaAvatar from '@web.awesome.me/webawesome-pro/dist/components/avatar/avatar.js';
import type RWaBadge from '@web.awesome.me/webawesome-pro/dist/components/badge/badge.js';
import type RWaBarChart from '@web.awesome.me/webawesome-pro/dist/components/bar-chart/bar-chart.js';
import type RWaBreadcrumb from '@web.awesome.me/webawesome-pro/dist/components/breadcrumb/breadcrumb.js';
import type RWaBreadcrumbItem from '@web.awesome.me/webawesome-pro/dist/components/breadcrumb-item/breadcrumb-item.js';
import type RWaBubbleChart from '@web.awesome.me/webawesome-pro/dist/components/bubble-chart/bubble-chart.js';
import type RWaButton from '@web.awesome.me/webawesome-pro/dist/components/button/button.js';
import type RWaButtonGroup from '@web.awesome.me/webawesome-pro/dist/components/button-group/button-group.js';
import type RWaCallout from '@web.awesome.me/webawesome-pro/dist/components/callout/callout.js';
import type RWaCard from '@web.awesome.me/webawesome-pro/dist/components/card/card.js';
import type RWaCarousel from '@web.awesome.me/webawesome-pro/dist/components/carousel/carousel.js';
import type RWaCarouselItem from '@web.awesome.me/webawesome-pro/dist/components/carousel-item/carousel-item.js';
import type RWaChart from '@web.awesome.me/webawesome-pro/dist/components/chart/chart.js';
import type RWaCheckbox from '@web.awesome.me/webawesome-pro/dist/components/checkbox/checkbox.js';
import type RWaColorPicker from '@web.awesome.me/webawesome-pro/dist/components/color-picker/color-picker.js';
import type RWaCombobox from '@web.awesome.me/webawesome-pro/dist/components/combobox/combobox.js';
import type RWaComparison from '@web.awesome.me/webawesome-pro/dist/components/comparison/comparison.js';
import type RWaCopyButton from '@web.awesome.me/webawesome-pro/dist/components/copy-button/copy-button.js';
import type RWaDetails from '@web.awesome.me/webawesome-pro/dist/components/details/details.js';
import type RWaDialog from '@web.awesome.me/webawesome-pro/dist/components/dialog/dialog.js';
import type RWaDivider from '@web.awesome.me/webawesome-pro/dist/components/divider/divider.js';
import type RWaDoughnutChart from '@web.awesome.me/webawesome-pro/dist/components/doughnut-chart/doughnut-chart.js';
import type RWaDrawer from '@web.awesome.me/webawesome-pro/dist/components/drawer/drawer.js';
import type RWaDropdown from '@web.awesome.me/webawesome-pro/dist/components/dropdown/dropdown.js';
import type RWaDropdownItem from '@web.awesome.me/webawesome-pro/dist/components/dropdown-item/dropdown-item.js';
import type RWaFileInput from '@web.awesome.me/webawesome-pro/dist/components/file-input/file-input.js';
import type RWaFormatBytes from '@web.awesome.me/webawesome-pro/dist/components/format-bytes/format-bytes.js';
import type RWaFormatDate from '@web.awesome.me/webawesome-pro/dist/components/format-date/format-date.js';
import type RWaFormatNumber from '@web.awesome.me/webawesome-pro/dist/components/format-number/format-number.js';
import type RWaIcon from '@web.awesome.me/webawesome-pro/dist/components/icon/icon.js';
import type RWaInclude from '@web.awesome.me/webawesome-pro/dist/components/include/include.js';
import type RWaInput from '@web.awesome.me/webawesome-pro/dist/components/input/input.js';
import type RWaIntersectionObserver from '@web.awesome.me/webawesome-pro/dist/components/intersection-observer/intersection-observer.js';
import type RWaLineChart from '@web.awesome.me/webawesome-pro/dist/components/line-chart/line-chart.js';
import type RWaMarkdown from '@web.awesome.me/webawesome-pro/dist/components/markdown/markdown.js';
import type RWaMutationObserver from '@web.awesome.me/webawesome-pro/dist/components/mutation-observer/mutation-observer.js';
import type RWaNumberInput from '@web.awesome.me/webawesome-pro/dist/components/number-input/number-input.js';
import type RWaOption from '@web.awesome.me/webawesome-pro/dist/components/option/option.js';
import type RWaPage from '@web.awesome.me/webawesome-pro/dist/components/page/page.js';
import type RWaPieChart from '@web.awesome.me/webawesome-pro/dist/components/pie-chart/pie-chart.js';
import type RWaPolarAreaChart from '@web.awesome.me/webawesome-pro/dist/components/polar-area-chart/polar-area-chart.js';
import type RWaPopover from '@web.awesome.me/webawesome-pro/dist/components/popover/popover.js';
import type RWaPopup from '@web.awesome.me/webawesome-pro/dist/components/popup/popup.js';
import type RWaProgressBar from '@web.awesome.me/webawesome-pro/dist/components/progress-bar/progress-bar.js';
import type RWaProgressRing from '@web.awesome.me/webawesome-pro/dist/components/progress-ring/progress-ring.js';
import type RWaQrCode from '@web.awesome.me/webawesome-pro/dist/components/qr-code/qr-code.js';
import type RWaRadarChart from '@web.awesome.me/webawesome-pro/dist/components/radar-chart/radar-chart.js';
import type RWaRadio from '@web.awesome.me/webawesome-pro/dist/components/radio/radio.js';
import type RWaRadioGroup from '@web.awesome.me/webawesome-pro/dist/components/radio-group/radio-group.js';
import type RWaRating from '@web.awesome.me/webawesome-pro/dist/components/rating/rating.js';
import type RWaRelativeTime from '@web.awesome.me/webawesome-pro/dist/components/relative-time/relative-time.js';
import type RWaResizeObserver from '@web.awesome.me/webawesome-pro/dist/components/resize-observer/resize-observer.js';
import type RWaScatterChart from '@web.awesome.me/webawesome-pro/dist/components/scatter-chart/scatter-chart.js';
import type RWaScroller from '@web.awesome.me/webawesome-pro/dist/components/scroller/scroller.js';
import type RWaSelect from '@web.awesome.me/webawesome-pro/dist/components/select/select.js';
import type RWaSkeleton from '@web.awesome.me/webawesome-pro/dist/components/skeleton/skeleton.js';
import type RWaSlider from '@web.awesome.me/webawesome-pro/dist/components/slider/slider.js';
import type RWaSparkline from '@web.awesome.me/webawesome-pro/dist/components/sparkline/sparkline.js';
import type RWaSpinner from '@web.awesome.me/webawesome-pro/dist/components/spinner/spinner.js';
import type RWaSplitPanel from '@web.awesome.me/webawesome-pro/dist/components/split-panel/split-panel.js';
import type RWaSwitch from '@web.awesome.me/webawesome-pro/dist/components/switch/switch.js';
import type RWaTab from '@web.awesome.me/webawesome-pro/dist/components/tab/tab.js';
import type RWaTabGroup from '@web.awesome.me/webawesome-pro/dist/components/tab-group/tab-group.js';
import type RWaTabPanel from '@web.awesome.me/webawesome-pro/dist/components/tab-panel/tab-panel.js';
import type RWaTag from '@web.awesome.me/webawesome-pro/dist/components/tag/tag.js';
import type RWaTextarea from '@web.awesome.me/webawesome-pro/dist/components/textarea/textarea.js';
import type RWaToast from '@web.awesome.me/webawesome-pro/dist/components/toast/toast.js';
import type RWaToastItem from '@web.awesome.me/webawesome-pro/dist/components/toast-item/toast-item.js';
import type RWaTooltip from '@web.awesome.me/webawesome-pro/dist/components/tooltip/tooltip.js';
import type RWaTree from '@web.awesome.me/webawesome-pro/dist/components/tree/tree.js';
import type RWaTreeItem from '@web.awesome.me/webawesome-pro/dist/components/tree-item/tree-item.js';
import type RWaVideo from '@web.awesome.me/webawesome-pro/dist/components/video/video.js';
import type RWaVideoPlaylist from '@web.awesome.me/webawesome-pro/dist/components/video-playlist/video-playlist.js';
import type RWaZoomableFrame from '@web.awesome.me/webawesome-pro/dist/components/zoomable-frame/zoomable-frame.js';

export type WaAnimatedImage = RWaAnimatedImage & LitElement;
export type WaAnimation = RWaAnimation & LitElement;
export type WaAvatar = RWaAvatar & LitElement;
export type WaBadge = RWaBadge & LitElement;
export type WaBarChart = RWaBarChart & LitElement;
export type WaBreadcrumb = RWaBreadcrumb & LitElement;
export type WaBreadcrumbItem = RWaBreadcrumbItem & LitElement;
export type WaBubbleChart = RWaBubbleChart & LitElement;
export type WaButton = RWaButton & LitElement;
export type WaButtonGroup = RWaButtonGroup & LitElement;
export type WaCallout = RWaCallout & LitElement;
export type WaCard = RWaCard & LitElement;
export type WaCarousel = RWaCarousel & LitElement;
export type WaCarouselItem = RWaCarouselItem & LitElement;
export type WaChart = RWaChart & LitElement;
export type WaCheckbox = RWaCheckbox & LitElement;
export type WaColorPicker = RWaColorPicker & LitElement;
export type WaCombobox = RWaCombobox & LitElement;
export type WaComparison = RWaComparison & LitElement;
export type WaCopyButton = RWaCopyButton & LitElement;
export type WaDetails = RWaDetails & LitElement;
export type WaDialog = RWaDialog & LitElement;
export type WaDivider = RWaDivider & LitElement;
export type WaDoughnutChart = RWaDoughnutChart & LitElement;
export type WaDrawer = RWaDrawer & LitElement;
export type WaDropdown = RWaDropdown & LitElement;
export type WaDropdownItem = RWaDropdownItem & LitElement;
export type WaFileInput = RWaFileInput & LitElement;
export type WaFormatBytes = RWaFormatBytes & LitElement;
export type WaFormatDate = RWaFormatDate & LitElement;
export type WaFormatNumber = RWaFormatNumber & LitElement;
export type WaIcon = RWaIcon & LitElement;
export type WaInclude = RWaInclude & LitElement;
export type WaInput = RWaInput & LitElement;
export type WaIntersectionObserver = RWaIntersectionObserver & LitElement;
export type WaLineChart = RWaLineChart & LitElement;
export type WaMarkdown = RWaMarkdown & LitElement;
export type WaMutationObserver = RWaMutationObserver & LitElement;
export type WaNumberInput = RWaNumberInput & LitElement;
export type WaOption = RWaOption & LitElement;
export type WaPage = RWaPage & LitElement;
export type WaPieChart = RWaPieChart & LitElement;
export type WaPolarAreaChart = RWaPolarAreaChart & LitElement;
export type WaPopover = RWaPopover & LitElement;
export type WaPopup = RWaPopup & LitElement;
export type WaProgressBar = RWaProgressBar & LitElement;
export type WaProgressRing = RWaProgressRing & LitElement;
export type WaQrCode = RWaQrCode & LitElement;
export type WaRadarChart = RWaRadarChart & LitElement;
export type WaRadio = RWaRadio & LitElement;
export type WaRadioGroup = RWaRadioGroup & LitElement;
export type WaRating = RWaRating & LitElement;
export type WaRelativeTime = RWaRelativeTime & LitElement;
export type WaResizeObserver = RWaResizeObserver & LitElement;
export type WaScatterChart = RWaScatterChart & LitElement;
export type WaScroller = RWaScroller & LitElement;
export type WaSelect = RWaSelect & LitElement;
export type WaSkeleton = RWaSkeleton & LitElement;
export type WaSlider = RWaSlider & LitElement;
export type WaSparkline = RWaSparkline & LitElement;
export type WaSpinner = RWaSpinner & LitElement;
export type WaSplitPanel = RWaSplitPanel & LitElement;
export type WaSwitch = RWaSwitch & LitElement;
export type WaTab = RWaTab & LitElement;
export type WaTabGroup = RWaTabGroup & LitElement;
export type WaTabPanel = RWaTabPanel & LitElement;
export type WaTag = RWaTag & LitElement;
export type WaTextarea = RWaTextarea & LitElement;
export type WaToast = RWaToast & LitElement;
export type WaToastItem = RWaToastItem & LitElement;
export type WaTooltip = RWaTooltip & LitElement;
export type WaTree = RWaTree & LitElement;
export type WaTreeItem = RWaTreeItem & LitElement;
export type WaVideo = RWaVideo & LitElement;
export type WaVideoPlaylist = RWaVideoPlaylist & LitElement;
export type WaZoomableFrame = RWaZoomableFrame & LitElement;
